version: '1.0'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432-5432'
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    container_name: maaad-heroku
    build: .
    depends_on:
      - db
    ports:
      - 3002:8080
    links:
      - db
volumes:
  db:
    driver: local